version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gympal-postgres-dev
    environment:
      POSTGRES_DB: gympal_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - gympal-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: gympal-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gympal-network

  # Supabase Local Development
  supabase:
    image: supabase/postgres:15.1.0.117
    container_name: gympal-supabase-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data
    networks:
      - gympal-network

  # Supabase Studio (Local Dashboard)
  supabase-studio:
    image: supabase/studio:20231218-2b8b8b8
    container_name: gympal-supabase-studio-dev
    environment:
      SUPABASE_URL: http://supabase:5432
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    ports:
      - "3001:3000"
    depends_on:
      - supabase
    networks:
      - gympal-network

  # GymPal Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: gympal-api-dev
    environment:
      NODE_ENV: development
      PORT: 3000
      SUPABASE_URL: http://supabase:5432
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      JWT_SECRET: development_jwt_secret_key_minimum_32_characters_long
      JWT_EXPIRY: 7d
      CORS_ORIGIN: http://localhost:3000,http://localhost:3001,http://localhost:5173
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
      - supabase
    networks:
      - gympal-network
    command: pnpm run dev

volumes:
  postgres_data:
  redis_data:
  supabase_data:

networks:
  gympal-network:
    driver: bridge
